# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "cs/Rileysoft.DotHack/Rileysoft.DotHack/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Dependencies: "
  - package-ecosystem: "nuget"
    directory: "cs/Rileysoft.DotHack/Rileysoft.DotHack.Tests/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Dependencies: "
  - package-ecosystem: "nuget"
    directory: "cs/Rileysoft.DotHack/Rileysoft.DotHack.IOTests/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Dependencies: "
  - package-ecosystem: "nuget"
    directory: "cs/Rileysoft.DotHack/ElfInfo/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Dependencies: "
